language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t swatikothari/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true swatikothari/docker-react npm run test